v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
N 115 -290 115 -270 { lab=GND}
N 115 -380 115 -350 { lab=dvdd}
N 115 -140 115 -120 { lab=GND}
N 115 -230 115 -200 { lab=vbg}
N 115 -460 115 -440 { lab=GND}
N 115 -550 115 -520 { lab=dvss}
N 745 -470 745 -450 { lab=#net1}
N 745 -560 745 -530 { lab=avdd}
N 615 -280 645 -280 {
lab=por}
N 615 -260 645 -260 {
lab=porb}
N 265 -460 265 -440 { lab=GND}
N 265 -550 265 -520 { lab=avss}
N 615 -240 645 -240 {
lab=porb_h[1:0]}
N 745 -390 745 -370 { lab=GND}
C {devices/title.sym} 160 -30 0 0 {name=l2 author="Stephen Wu"}
C {devices/gnd.sym} 115 -270 0 0 {name=l22 lab=GND}
C {devices/gnd.sym} 115 -120 0 0 {name=l3 lab=GND}
C {devices/vsource.sym} 115 -490 0 1 {name=Vdvss value="DC CACE\{Vdvss\}"}
C {devices/gnd.sym} 115 -440 0 0 {name=l5 lab=GND}
C {devices/lab_wire.sym} 115 -550 0 0 {name=p7 lab=dvss}
C {devices/gnd.sym} 745 -370 0 0 {name=l7 lab=GND}
C {devices/opin.sym} 645 -280 0 0 {name=p5 lab=por}
C {devices/opin.sym} 645 -260 0 0 {name=p6 lab=porb}
C {devices/lab_wire.sym} 455 -220 0 0 {name=p8 lab=vbg}
C {devices/lab_wire.sym} 455 -300 0 0 {name=p9 lab=avdd}
C {devices/lab_wire.sym} 455 -280 0 0 {name=p10 lab=dvdd}
C {devices/lab_wire.sym} 745 -560 0 0 {name=p11 lab=avdd}
C {devices/lab_wire.sym} 115 -380 0 0 {name=p12 lab=dvdd
}
C {devices/lab_wire.sym} 115 -230 0 0 {name=p17 lab=vbg}
C {devices/vsource.sym} 745 -500 2 0 {name=Vavdd value="PULSE 0 \{Vglitch\} 1m 0.5m 0.5m \{Vglitch_dur\} 1"}
C {devices/lab_wire.sym} 455 -260 0 0 {name=p20 lab=avss}
C {devices/lab_wire.sym} 455 -240 0 0 {name=p21 lab=dvss}
C {devices/vsource.sym} 265 -490 0 1 {name=Vavss value="DC CACE\{Vavss\}"}
C {devices/gnd.sym} 265 -440 0 0 {name=l8 lab=GND}
C {devices/lab_wire.sym} 265 -550 0 0 {name=p22 lab=avss}
C {devices/opin.sym} 645 -240 0 0 {name=p25 lab=porb_h[1:0]}
C {devices/vsource.sym} 115 -320 0 0 {name=Vdvdd value="DC CACE\{Vdvdd\}"}
C {devices/vsource.sym} 115 -170 0 0 {name=Vvbg value="DC CACE\{Vvbg\}"}
C {devices/code_shown.sym} 15 -980 0 0 {name=SETUP only_toplevel=false value="
* CACE gensim simulation file CACE\{filename\}
* Generated by CACE gensim, Efabless Corporation (c) 2024
* Find the powerup simulation of POR

.include CACE\{DUT_path\}
.include CACE\{PDK_ROOT\}/CACE\{PDK\}/libs.ref/sky130_fd_sc_hvl/spice/sky130_fd_sc_hvl.spice
.include CACE\{PDK_ROOT\}/CACE\{PDK\}/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice
.include CACE\{PDK_ROOT\}/CACE\{PDK\}/libs.ref/sky130_fd_sc_ls/spice/sky130_fd_sc_ls.spice

.lib CACE\{PDK_ROOT\}/CACE\{PDK\}/libs.tech/combined/sky130.lib.spice CACE\{corner\}
*.lib CACE\{PDK_ROOT\}/CACE\{PDK\}/libs.tech/ngspice/sky130.lib.spice CACE\{corner\}

.option TEMP=CACE\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/code_shown.sym} 985 -930 0 0 {name=CONTROL only_toplevel=false value=".param Vglitch = CACE\{Vavdd\}
.param Vglitch_dur = CACE\{Tsim\}

.tran CACE\{Tstep\} CACE\{Tsim\}

.control
let dvdd_half = 0.5*CACE\{Vdvdd\}
* glitch duration sweep loop
*let stop_dur = CACE\{Tsim\}
let stop_dur = 200u
let delta_dur = 5u
let dur_act = 10u
while dur_act le stop_dur
 alterparam Vglitch_dur = $&dur_act
 reset
 run
 meas tran por_val FIND v(por) AT = CACE\{Tsim\}
 if por_val > dvdd_half
   echo $&dur_act  > CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
   alterparam Vglitch_dur = $&dur_act
   let dur_act = dur_act + stop_dur
 else 
   let dur_act = dur_act + delta_dur
 end
end

* glitch amplitude sweep loop
let stop_amp = CACE\{Vavdd\}
let delta_amp = 100m
let amp_act = 100m
while amp_act le stop_amp
 alterparam Vglitch = $&amp_act
 reset
 run
 meas tran por_val FIND v(por) AT = CACE\{Tsim\}
 if por_val > dvdd_half
   echo $&amp_act  >> CACE\{simpath\}/CACE\{filename\}_CACE\{N\}.data
   let amp_act = amp_act + stop_amp
 else 
   let amp_act = amp_act + delta_amp
 end
end
quit
.endc
"}
C {sky130_sw_ip__bgrref_por.sym} 535 -260 0 0 {name=XDUT1}
C {devices/capa.sym} 830 -130 0 0 {name=C1
m=1
value=CACE\{CLb\}
footprint=1206
device="ceramic capacitor"}
C {devices/lab_wire.sym} 830 -160 0 1 {name=p1 lab=por}
C {devices/capa.sym} 730 -130 0 0 {name=C2
m=1
value=CACE\{CLb\}
footprint=1206
device="ceramic capacitor"}
C {devices/lab_wire.sym} 730 -160 0 1 {name=p19 lab=porb}
C {devices/gnd.sym} 730 -100 0 0 {name=l4 lab=GND}
C {devices/gnd.sym} 830 -100 0 0 {name=l1 lab=GND}
C {devices/capa.sym} 620 -130 0 0 {name=C3
m=1
value=CACE\{CLw\}
footprint=1206
device="ceramic capacitor"}
C {devices/lab_wire.sym} 620 -160 0 1 {name=p13 lab=porb_h[0]}
C {devices/gnd.sym} 620 -100 0 0 {name=l6 lab=GND}
C {devices/capa.sym} 520 -130 0 0 {name=C4
m=1
value=CACE\{CLw\}
footprint=1206
device="ceramic capacitor"}
C {devices/lab_wire.sym} 520 -160 0 1 {name=p14 lab=porb_h[1]}
C {devices/gnd.sym} 520 -100 0 0 {name=l9 lab=GND}
C {devices/vsource.sym} 745 -420 0 0 {name=Vavdd1 value="DC CACE\{Vavdd\}"}
