v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
N 650 -300 680 -300 {
lab=por}
N 650 -280 680 -280 {
lab=porb}
N 650 -260 680 -260 {
lab=porb_h}
N 110 -420 110 -400 { lab=GND}
N 110 -510 110 -480 { lab=dvdd}
N 110 -270 110 -250 { lab=GND}
N 110 -360 110 -330 { lab=vbg}
N 110 -590 110 -570 { lab=GND}
N 110 -680 110 -650 { lab=dvss}
N 260 -590 260 -570 { lab=GND}
N 260 -680 260 -650 { lab=avdd}
N 180 -590 180 -570 { lab=GND}
N 180 -680 180 -650 { lab=avss}
C {devices/title.sym} 160 -30 0 0 {name=l2 author="Stephen Wu"}
C {devices/opin.sym} 680 -300 0 0 {name=p13 lab=por}
C {devices/opin.sym} 680 -280 0 0 {name=p14 lab=porb}
C {devices/lab_wire.sym} 490 -240 0 0 {name=p16 lab=vbg}
C {devices/lab_wire.sym} 490 -320 0 0 {name=p18 lab=avdd}
C {devices/lab_wire.sym} 490 -300 0 0 {name=p19 lab=dvdd}
C {devices/lab_wire.sym} 490 -280 0 0 {name=p23 lab=avss}
C {devices/lab_wire.sym} 490 -260 0 0 {name=p24 lab=dvss}
C {devices/opin.sym} 680 -260 0 0 {name=p26 lab=porb_h}
C {sky130_sw_ip__bgrref_por.sym} 570 -280 0 0 {name=XDUT}
C {devices/code_shown.sym} 940 -330 0 0 {name=CONTROL1 only_toplevel=false value="
.control
.options savecurrents
save all

tran 1u 4m
meas tran yAvdd1 FIND v(avdd) When v(por)=0.9 RISE=1
meas tran yAvdd2 FIND v(avdd) WHEN V(por)=0.9 FALL=1
meas tran Ivdd AVG i(V10)
let hyst='yAvdd1-yAvdd2'
*  print hyst
*plot AVDD por porb+6.8 porb_h+3.4
wrdata \{simpath\}/\{filename\}_\{N\}.data hyst

quit
.endc
"}
C {devices/gnd.sym} 110 -400 0 0 {name=l1 lab=GND}
C {devices/gnd.sym} 110 -250 0 0 {name=l4 lab=GND}
C {devices/vsource.sym} 110 -620 0 1 {name=V9 value="0"}
C {devices/gnd.sym} 110 -570 0 0 {name=l9 lab=GND}
C {devices/lab_wire.sym} 110 -680 0 0 {name=p15 lab=dvss}
C {devices/gnd.sym} 260 -570 0 0 {name=l6 lab=GND}
C {devices/lab_wire.sym} 260 -680 0 0 {name=p1 lab=avdd}
C {devices/lab_wire.sym} 110 -510 0 0 {name=p2 lab=dvdd}
C {devices/lab_wire.sym} 110 -360 0 0 {name=p3 lab=vbg}
C {devices/vsource.sym} 260 -620 0 0 {name=V1 value="PULSE 0 3.3 10n 1m 1m 1m 4m"}
C {devices/vsource.sym} 180 -620 0 1 {name=V11 value="0"}
C {devices/gnd.sym} 180 -570 0 0 {name=l11 lab=GND}
C {devices/lab_wire.sym} 180 -680 0 0 {name=p4 lab=avss}
C {devices/vsource.sym} 110 -450 0 0 {name=V2 value="PULSE 0 1.8 10n 1.1m 1m 0.9m 4m"}
C {devices/vsource.sym} 110 -300 0 0 {name=V3 value="PULSE 0 1.2 10n 0.5m 0.5m 2m 4m"}
C {devices/code_shown.sym} 920 -680 0 0 {name=SETUP only_toplevel=false value="
* CACE gensim simulation file \{filename\}
* Generated by CACE gensim, Efabless Corporation (c) 2024
* Find the powerup simulation of POR

.include \{DUT_path\}
.include \{PDK_ROOT\}/\{PDK\}/libs.ref/sky130_fd_sc_hvl/spice/sky130_fd_sc_hvl.spice
.include \{PDK_ROOT\}/\{PDK\}/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice

*.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/combined/sky130.lib.spice \{corner\}
.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/ngspice/sky130.lib.spice \{corner\}

.option TEMP=\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
